### ISSUE TITLE
How to find ObjectId 

### ISSUE THREAD

**Issue by JAICHANGPARK** [mongo-dart/mongo_dart#145]
![image](https://user-images.githubusercontent.com/19484515/57570353-d5c71f80-743b-11e9-8c32-511ba6a40ae0.png)

```
var result = await collection.findOne(where.eq("_id", userID));
```
I tried this code, But not working for me 
How to find ObjectId using findOne ? 

Thanks :)

**Comment by thosakwe** [comment]
What specifically do you mean by "not working"?

Here are some options:
* Use `where.id(userID)`, instead of `where.eq("_id")`.
* You can create an `ObjectId` instance from a `String` using the `ObjectId.fromHexString` constructor.
* `Map`s returned from `mongo_dart` will have an `ObjectId` as the value for `"_id"`. For example:

```dart
var result = await collection.findOne(where.eq("_id", userID));
print(result['_id']);
```

**Comment by gitdefllo** [comment]
Converting to `ObjectId()` (bson) works perfectly: `where.id(ObjectId.parse(userId))`

**Comment by JAICHANGPARK** [comment]
@gitdefllo  Thank you
