### ISSUE TITLE
'masterConnectionVerified' was called on null

### ISSUE THREAD

**Issue by syfulin** [mongo-dart/mongo_dart#191]
What causes this error?
```
Unhandled exception:
NoSuchMethodError: The getter 'masterConnectionVerified' was called on null.
Receiver: null
Tried calling: masterConnectionVerified
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Db._masterConnectionVerified (package:mongo_dart/src/database/db.dart:134:26)
#2      Db.executeDbCommand (package:mongo_dart/src/database/db.dart:324:20)
<asynchronous suspension>
#3      DbCollection.findAndModify (package:mongo_dart/src/database/dbcollection.dart:91:10)
```

**Comment by giorgiofran** [comment]
Which version of mongo_dart are you using?

**Comment by giorgiofran** [comment]
Is it possible that you are calling `DbCollection.findAndModify` before opening the database (`await db.open()`)? Because the null object that your error reports (`_connectionManager`), is created during db.open and cleared in db.close, so it seems that your call to `findAndModify` must have been done when the database is not in state `OPEN`
May you please confirm this?

**Comment by giorgiofran** [comment]
I have modified the method so that it returns a clearer message and I close the issue. Feel free to reopen it if there is any other problem.
