### ISSUE TITLE
how to make collections relations mangodart? in flutter

### ISSUE THREAD

**Issue by ramsmart-inno** [mongo-dart/mongo_dart#205]

**Comment by giorgiofran** [comment]
Sorry, I couldn't get your question

**Comment by ramsmart-inno** [comment]
> Sorry, I couldn't get your question

For example, we have two collections like  "user" and "post".
- user have a fields of name, email, userid, bio,...etc
- post have a fields of userid, postdescription, timestamp,...etc

Now i need to make a relationship of user[userid] with post[userid] while querying.

**Comment by giorgiofran** [comment]
Still it is not completely clear what you would like to know, but I'll try a response.
First, consider that MongoDb is not a relation database. This means that you cannot define fixed relations between collections.
Second, all MongoDb documents have a unique key (so you do not need to have a specific userId field) called "`_id`". If you don't specify it, the system creates a new `ObjectId`  value for it, otherwise you can use the type you like (for example `String`).
This said, for querying the post collection for a specific user simply ask for all documents that have the search value in the userId field of the post collection.
a little documentation: https://docs.mongodb.com/manual/tutorial/model-referenced-one-to-many-relationships-between-documents/

**Comment by giorgiofran** [comment]
If what you need is a join between collections, please give a look to these links:
https://www.sitepoint.com/using-joins-in-mongodb-nosql-databases/
https://kb.objectrocket.com/mongo-db/how-to-do-a-join-using-the-mongodb-shell-202

**Comment by giorgiofran** [comment]
I close this bug, feel free to open a new issue if needed.
