### ISSUE TITLE
I'm new to this, I just want to see how to pass multiple parameters

### ISSUE THREAD

**Issue by EthanDamien** [mongo-dart/mongo_dart#210]
I am watching this [tutorial](https://youtu.be/juKDXPk7kU4?t=510) where he is setting up the server and passing a single parameter in the document. I want to know how to pass multiple parameters using: 
`curl -X POST -H "Content-Type: application/json" -d '{"name": "Ethan","dob":"09/13/2001"}' http://localost:8001`

I don't know how to do this and if anyone could let me know I would really appreciate it... So far I have this.
```
serv.post('/', [
    (ServRequest req, ServResponse res) async {
      await coll.save(req.body);
      return res.json(
        await coll.findOne({
          where.eq('gender', req.body['gender']),
        }),
      );
    }
  ]);
```

**Comment by num8er** [comment]
I guess You're asking how to pass multiple query params?

If YES so it's written in examples [here](https://github.com/mongo-dart/mongo_dart#querying) and since every method of query builder returns instance of [SelectorBuilder](https://github.com/mongo-dart/mongo_dart_query/blob/master/lib/src/selector_builder.dart) You can chain methods like:

```
await coll.findOne(
  where
    .eq('gender', req.body['gender'])
    .eq('name', req.body['name'])
),
```

**Comment by giorgiofran** [comment]
I close this bug, feel free to open a new issue if needed.
