### ISSUE TITLE
MongoDart Error: Db is in the wrong state: State.INIT

### ISSUE THREAD

**Issue by malengatiger** [mongo-dart/mongo_dart#234]
I am using flutter and running aground trying  to connect to MongoDB Atlas database.  The error occurs when I call Db.create() with the following connection string: 

**mongodb://<user>:<password>@ar001-shard-00-00.1xhdt.mongodb.net:27017,ar001-shard-00-01.1xhdt.mongodb.net:27017,ar001-shard-00-00.1xhdt.mongodb.net:27017/upassdb?authSource=admin&replicaSet=AR001**

the plugin throws a fit: MongoDart Error: Db is in the wrong state: State.INIT

Thanks for the help!

**Comment by giorgiofran** [comment]
Without a snippet of code is difficult to say. The first thought is that you forgot to await the `db.create` call.
Anyway, give a look to a "fast and furious" example for testing atlas connection in flutter in issue #193 .

**Comment by giorgiofran** [comment]
I close this issue, feel free to re-open it if needed.

**Comment by Frael98** [comment]
Hello, good day, I don't know if this issue was resolved, I got a similar error in my app.
I tried all kind of solutions, but I got no solution, this is my log:

![image](https://github.com/mongo-dart/mongo_dart/assets/52361906/9e8af9f3-f5c4-404c-9748-faa38a746ff6)

This is my class:

`class DBConnection {
  static DBConnection? _instance;
  final String _host = "localhost";
  final String _port = "27017";
  final String _dbName = "msi_dart";
  Db? _db;

  static getInstance() {
    _instance ??= DBConnection();
    return _instance;
  }

  Future<Db?> getConnection() async {
    if (_db == null) {
      try {
        _db = await Db.create(_getConnectionString());
      } catch (e) {
        log("Error getConnection: $e");
      }
    }
    return _db;
  }

  String _getConnectionString() {
    return "mongodb://frael:root@$_host:$_port/$_dbName";
  }

  void closeConnection() {
    _db?.close();
  }

  static void main() async {
    final db = await DBConnection().getConnection();

    try {
      await db!.open();
      var userCollection = db.collection('user');
      userCollection.find().forEach((element) {
        log(element.toString());
      });
    } catch (e) {
      log("Error main: $e");
    }
  }
}`

I don't know if this has anything to do with it, but I always get a different port in the error.
**Connection refused, errno = 111), address = localhost, port = 41926**

I do can connect to my db using MongoCompass and mongosh

![image](https://github.com/mongo-dart/mongo_dart/assets/52361906/359ceb72-1345-4eab-b029-74241caa94d7)

My project's dependencies:

![image](https://github.com/mongo-dart/mongo_dart/assets/52361906/c84ce083-183a-4264-a626-46c197c37cbb)

Thank you for your attention!

**Comment by giorgiofran** [comment]
Web app or running in the emulator?

**Comment by Frael98** [comment]
It's an Emulator!, I have tried with different mongo dart versions, thank you

**Comment by giorgiofran** [comment]
Please, give a look to #193

**Comment by Frael98** [comment]
Thank you very much for your kind help.
I have solved the problem in the following way.

The adb tool also allows me to map ports with the emulator and my machine

With this command

`adb -a reverse tcp:27017 tcp27017`

I map the ports and I don't have to change the host in my connection settings.

I leave the link to the command, in case anyone has the same problem
[Android Debug Bridge Reverse: reverse socket connections from an Android emulator instance or connected Android devices](https://www.thegeekdiary.com/adb-reverse-android-debug-bridge-reverse-reverse-socket-connections-from-an-android-emulator-instance-or-connected-android-devices/)

I have also read the post you recommended, and I find it interesting.
