### ISSUE TITLE
db.open() takes ages to complete

### ISSUE THREAD

**Issue by shambhav91** [mongo-dart/mongo_dart#262]
I'm connecting my Mongo Atlas DB to my flutter app through mongo_dart ^0.7.4 but it takes about 10 seconds to finish connecting to the database. On further inspection I found the line db.open() takes around 8-9 seconds to execute. I tried the same thing on Python and it only took 0.27 seconds to complete. Am I missing something or doing anything incorrectly as 10 seconds feels like a huge amount of time to make the connection!

Dart Code:
```
var t0 = DateTime.now().millisecondsSinceEpoch;
var db = await Db.create("mongodb+srv://<username>:<password>@<hostname>/<dbname>?retryWrites=true&w=majority");
var t1 = DateTime.now().millisecondsSinceEpoch;
print("Connect: ${t1-t0}");
await db.open();
var t2 = DateTime.now().millisecondsSinceEpoch;
print("Open: ${t2-t1}");
print("Total: ${t2-t0}");
```

Python Code:
```
mongo_client = pymongo.MongoClient("mongodb+srv://<username>:<password>@<hostname>/<dbname>")
db = mongo_client[db_name]
collection = db[collection_name]

```

**Comment by giorgiofran** [comment]
I did some testing, and my results are that a connection to Atlas takes an average one second.
I run exactly your test with my connection string.
There are a couple of considerations to be done:
- Atlas still does not support a scram-256 connection that is the default that the mongo-dart driver uses due to the mongoDb version it is connected (equal or greater of 4.0). If the first connection returns error, the driver tries again with scram-1 protocol. This attempt takes a little time (not so much). If you wanna try to connect directly with scram-1 you can add a parameter in the connection string like the following:  `?authMechanism=SCRAM-SHA-1&retryWrites=true&w=majority`

- The communication with atlas is made in two phases: the first is to discover the real addresses behind the connection string (in a normal replica set you'll have three server addresses). This is done n  Db.create(). The second is the proper connection. In my test case I have three servers, and for each of them it takes approximately 0.3 seconds to connect. Multiply by three and add the previous step, and you are near the second.

Given these results I guess that the Python driver returns immediately after connecting with the first server.

This said, I had not to wait for 10 seconds. If you can do further testing and discover which is the problem I'd be glad.

**Comment by giorgiofran** [comment]
Do you still have the problem? Can I close the issue?

**Comment by giorgiofran** [comment]
I hope that you solved the problem. I close this issue.
