### ISSUE TITLE
Can't connect to digital Digital Ocean from local Mac

### ISSUE THREAD

**Issue by booper** [mongo-dart/mongo_dart#270]
Trying to connect to DO Managed MongoDB and got the error:

```
Exception has occurred.
ConnectionException (MongoDB ConnectionException: Could not connect to XXX.mongo.ondigitalocean.com:27017
- HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393)))
```

I've read this [manual](https://github.com/mongo-dart/mongo_dart/blob/main/doc/manual/connection/simple_connection_no_auth.md) but didn't help

my MacOS BigSure 11.6.2 Intel

when I use "mongo" command with the same connection string and cert file, it is connected just fine 

May you help me?

**Comment by giorgiofran** [comment]
Unfortunately, it is difficult to say. From the message it seems that the problem is in the certificate.
Are you sure that you are passing the same certificate as in the `mongo` connection?
Try to add the certificate to the certificate store. And check again.
If you have a linux or windows computer also, try to connect from these.

Just guessing, in this case even debugging is not easy, because the error seems to come from OS level routines.
Eventually try to put the debug and see if in the original message there is some more explanation.
Check the system log to see if there is any explanation...

Sorry, I know that these are all desperate tries, but it is difficult to guess whats happening.

Probably it is worth to concentrate on the certificate (is the correct one, is it passed correctly ...), and so on.

Let me know if you discover the problem.

**Comment by booper** [comment]
Run on Linux ( Ubuntu 20.04.2. )
```
Unhandled exception:
MongoDart Error: Authentication failed.
#0      _ConnectionManager.open (package:mongo_dart/src/network/connection_manager.dart:148)
<asynchronous suspension>
#1      Db.open (package:mongo_dart/src/database/db.dart:459)
<asynchronous suspension>
```

> Are you sure that you are passing the same certificate as in the mongo connection?

Yes, I am sure, I use the same file of the certificate.  I don't think it is something about the certificate. It is 100% ok, something wrong with Auth in code.

**Comment by giorgiofran** [comment]
Do you use the the connection string option or the `db.open` parameter?
Ex.  
`await db.open(secure: true, tlsCAFile: caCertFile.path);`

I have time for debugging only on Saturday ...

**Comment by booper** [comment]
what is the best way to send them to you?

**Comment by booper** [comment]
since  I use a Mac as dev env, I just use 

` await db.open(tlsAllowInvalidCertificates: true);`

And now it's working just fine. This is the solution for a development environment.  Don't use it on production.
