### ISSUE TITLE
What is the reason - SocketException 

### ISSUE THREAD

**Issue by WONDERJEWEL** [mongo-dart/mongo_dart#277]
What is the reason for this exception?

SocketException: Software caused connection abort (OS Error: Software caused connection abort, errno = 103),
 address = cluster0-shard-00-02.XXXXXXXXX.mongodb.net, port = 42848
 
 **My connection string -** 
 cluster0.XXXXX.mongodb.net,
 cluster0-shard-00-00.XXXXXX.mongodb.net:27017,
 cluster0-shard-00-01.XXXXX.mongodb.net:27017,
 cluster0-shard-00-02.XXXXXXX.mongodb.net:27017..........

**Comment by giorgiofran** [comment]
It is difficoult to say. It is strange to me that the error refers to port 42848 while your connection string only have port 27017.

**Comment by giorgiofran** [comment]
I close this issue, feel free to reopen it if needed

**Comment by steel-yourself** [comment]
I get this **SocketException** as well, although in my case I have identified the source:

It happens when my device loses network connectivity while a connection to the database is open.  Is there a way to catch and handle this **SocketException**?  Currently we are running/testing in debug mode--will this **SocketException** cause issues when in release mode?
