### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by ghost** [mongo-dart/mongo_dart#35]
Add SSL Support in the Dart driver to enable encrypted connections to mongod instances.

http://docs.mongodb.org/manual/tutorial/configure-ssl/

**Comment by giorgiofran** [comment]
Did you change your plans about SSL? May I eventually cooperate in developing this function?

**Comment by vadimtsushko** [comment]
Hi.
It's not if I somehow against SSL support for mongo_dart. I just realistically assess resources of my spare time for this and do not see such opportunity for myself in foreseable future.
I definitely totally for it, if for example you take this task upon yourself.
I'll try to help if some help would be neseccary, but blunt of actual developing and testing would be on you.

**Comment by vadimtsushko** [comment]
By the way, it is totally possibly that actual modification would big anyway.
Or it may be considerable - I do not know. Testing probably is serious problem anyway

**Comment by giorgiofran** [comment]
Hi Vadim,

    I'd need this functionality, so I will definitely give a look to it.
I will have some time only after mid October.
In general I have not so much time, so I hope that not so much effort is 
needed in order to implement this functionality, otherwise I 'll have to 
give up.
Hope that you can give me some hints, as I did not have time to examine 
the sources up to now.
More, I have never implemented an SSL layer, so I hope that I can 
understand how it works giving a look to the javascript driver.
How did you started? Did you understand the logic looking at some 
existing driver, or did you have some documentation?

Bye,
    Giorgio

Il 31/08/2015 13:40, Vadim Tsushko ha scritto:

**Comment by Pacane** [comment]
@giorgiofran If you're still interested in contributing this, let me know, I could give you some help. I have never implemented an SSL layer, but that won't stop us ;)

**Comment by giorgiofran** [comment]
Thanks Joel,

  unfortunately I have not time to dedicate to this development at present.

May be next year. In the meanwhile, if you want to start, feel free to 
do it.

I never implemented an SSL layer too ;-)

Regards,
   Giorgio



Il 24/11/2015 04:20, Joel Trottier-Hebert ha scritto:

**Comment by tgercek** [comment]
#147 will address generic SSL issues.

**Comment by giorgiofran** [comment]
SSL added.
