### ISSUE TITLE
error while getting document - Binary subtype "3" is not yet managed

### ISSUE THREAD

**Issue by kaliosek** [mongo-dart/mongo_dart#367]
Hi there,
when I try to receive documents I have error: Binary subtype "3" is not yet managed

This is what I found:
The error MongoDB ConnectionException: connection closed: Invalid argument(s): Binary subtype "3" is not yet managed is related to the mongo_dart package used in your Flutter project. This error typically occurs when the MongoDB driver encounters a binary data type with a subtype that it does not recognize or support.  In MongoDB, the Binary data type can have different subtypes. Subtype 3 is used for the UUID old, which is the legacy encoding. 

Any way to handle this case?

In my way I am trying to connect to existing database and I am not able to change the types in database.

**Comment by giorgiofran** [comment]
The binary type 3 UUID is somehow deprecated. The problem is that UUID Binary sub-type 3 is strictly related to the driver that wrote it.
Give a look to [here](https://studio3t.com/knowledge-base/articles/mongodb-best-practices-uuid-data/).
Eventually I could return it as a binary and then you apply the conversion rule that you do prefer.
But, as you have seen, at present it is not managed from the driver.

**Comment by kaliosek** [comment]
Ok in my case there will be .net version. But it will be ok for me to do the conversion on my side. If document will be received. Now I cannot read any.

**Comment by giorgiofran** [comment]
I updated the Bson package, that holds the logic related to Bson serialization.
Now there is a new class that you can pass as a value to the system to manage old Uuid types.
The name of the class is: LegacyUuid.  This class holds the value in the format that will be sent to the server.
In the internet I found the description of how the different drivers where storing the Uuid, so I prepared also some convenient methods to store the value and to retrieve it.
In your case you should use the cSharpLegacy helpers. For example:
``` dart
  await collection.insertOne({
          'cSharpLegacy': LegacyUuid.toCSharpLegacy(uuidValue),
        });
```
You can also create the LegacyUuid instance with a Uuid string representation.

Once you retrieve the LegacyUuid instance, you can get back the correct UuidValue:
`(map['cSharpLegacy'] as LegacyUuid).cSharpLegacy`

I cannot publish immediately a new version of mongo_dart because I'm doing some other changes, but, as the new feature is in the package Bson, you should be able to use it updating the dependencies of you project.

Please, give it a try and let me know if everything is working as expected!

**Comment by giorgiofran** [comment]
Version 0.10.1 has been released.
